#spring:
#  datasource:
#    url: jdbc:mysql://106.14.105.101:3306/qiniu_short_video?useSSL=false
#    username: root
#    password: qwer1234
#    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.qiniu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
